# Generated by Django 4.0.4 on 2022-04-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_newinfo_id_alter_newinfo_adress_alter_newinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinfo',
            name='adress',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='cite',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='city',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Абакан', 'Абакан'), ('Екатеринбург', 'Екатеринбург'), ('Магадан', 'Магадан'), ('Магнитогорск', 'Магнитогорск'), ('Ижевск', 'Ижевск'), ('Набережные Челны', 'Набережные Челны'), ('Сочи', 'Сочи'), ('Йошкар-Ола', 'Йошкар-Ола'), ('Балашиха', 'Балашиха'), ('Барнаул', 'Барнаул'), ('Белгород', 'Белгород'), ('Казань', 'Казань'), ('Иваново', 'Иваново'), ('Мурманск', 'Мурманск'), ('Симферополь', 'Симферополь'), ('Ставрополь', 'Ставрополь'), ('Сургут', 'Сургут'), ('Калуга', 'Калуга'), ('Нижний Новгород', 'Нижний Новгород'), ('Тверь', 'Тверь'), ('Тамбов', 'Тамбов'), ('Благовещенск', 'Благовещенск'), ('Новокузнецк', 'Новокузнецк'), ('Новосибирск', 'Новосибирск'), ('Новороссийск', 'Новороссийск'), ('Томск', 'Томск'), ('Тольятти', 'Тольятти'), ('Тюмень', 'Тюмень'), ('Одесса', 'Одесса'), ('Омск', 'Омск'), ('Орск', 'Орск'), ('Хабаровск', 'Хабаровск'), ('Пенза', 'Пенза'), ('Краснодар', 'Краснодар'), ('Петрозаводск', 'Петрозаводск'), ('Чебоксары', 'Чебоксары'), ('Череповец', 'Череповец'), ('Челябинск', 'Челябинск'), ('Псков', 'Псков'), ('Пятигорск', 'Пятигорск'), ('Красноярск', 'Красноярск'), ('Самара', 'Самара'), ('Рыбинск', 'Рыбинск'), ('Ярославль', 'Ярославль'), ('Якутск', 'Якутск'), ('Южно-Сахалинск', 'Южно-Сахалинск'), ('Липецк', 'Липецк'), ('Саратов', 'Саратов'), ('Ростов-на-Дону', 'Ростов-на-Дону'), ('Санкт-Петербург', 'Санкт-Петербург')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='phone_numbers',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='price',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='types',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='url_istochnik',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='vmestimost',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='adress',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='cite',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='city',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Абакан', 'Абакан'), ('Екатеринбург', 'Екатеринбург'), ('Магадан', 'Магадан'), ('Магнитогорск', 'Магнитогорск'), ('Ижевск', 'Ижевск'), ('Набережные Челны', 'Набережные Челны'), ('Сочи', 'Сочи'), ('Йошкар-Ола', 'Йошкар-Ола'), ('Балашиха', 'Балашиха'), ('Барнаул', 'Барнаул'), ('Белгород', 'Белгород'), ('Казань', 'Казань'), ('Иваново', 'Иваново'), ('Мурманск', 'Мурманск'), ('Симферополь', 'Симферополь'), ('Ставрополь', 'Ставрополь'), ('Сургут', 'Сургут'), ('Калуга', 'Калуга'), ('Нижний Новгород', 'Нижний Новгород'), ('Тверь', 'Тверь'), ('Тамбов', 'Тамбов'), ('Благовещенск', 'Благовещенск'), ('Новокузнецк', 'Новокузнецк'), ('Новосибирск', 'Новосибирск'), ('Новороссийск', 'Новороссийск'), ('Томск', 'Томск'), ('Тольятти', 'Тольятти'), ('Тюмень', 'Тюмень'), ('Одесса', 'Одесса'), ('Омск', 'Омск'), ('Орск', 'Орск'), ('Хабаровск', 'Хабаровск'), ('Пенза', 'Пенза'), ('Краснодар', 'Краснодар'), ('Петрозаводск', 'Петрозаводск'), ('Чебоксары', 'Чебоксары'), ('Череповец', 'Череповец'), ('Челябинск', 'Челябинск'), ('Псков', 'Псков'), ('Пятигорск', 'Пятигорск'), ('Красноярск', 'Красноярск'), ('Самара', 'Самара'), ('Рыбинск', 'Рыбинск'), ('Ярославль', 'Ярославль'), ('Якутск', 'Якутск'), ('Южно-Сахалинск', 'Южно-Сахалинск'), ('Липецк', 'Липецк'), ('Саратов', 'Саратов'), ('Ростов-на-Дону', 'Ростов-на-Дону'), ('Санкт-Петербург', 'Санкт-Петербург')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='istochnik',
            field=models.CharField(choices=[('vsaunah', 'Vsaunah'), ('bannik', 'Bannik'), ('101sauna', '101sauna'), ('banya', 'Banya'), ('dvhab', 'Dvhab'), ('sauna_rest', 'Sauna_rest'), ('vsaunu', 'Vsaunu'), ('zoon', 'Zoon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='phone_numbers',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='photos',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='price',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='types',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='vmestimost',
            field=models.TextField(null=True),
        ),
    ]
