# Generated by Django 4.0.4 on 2022-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_alter_newinfo_adress_alter_newinfo_cite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinfo',
            name='photos',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='oldinfo',
            name='photos',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
